// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260925054643_AddActivityLogTable")]
    partial class AddActivityLogTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend.Entities.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AdminId"));

                    b.Property<string>("AccessLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SecurePinHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("AdminId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("Backend.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Hotel / Venue",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Photography",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Music",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Decorations",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Catering",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Backend.Entities.CateringDetails", b =>
                {
                    b.Property<int>("ServiceId")
                        .HasColumnType("integer");

                    b.Property<bool?>("ChafingDishesIncluded")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CrockeryCutlery")
                        .HasColumnType("text");

                    b.Property<string[]>("Cuisines")
                        .HasColumnType("text[]");

                    b.Property<string[]>("DietaryOptions")
                        .HasColumnType("text[]");

                    b.Property<bool?>("FurnitureRentalAvailable")
                        .HasColumnType("boolean");

                    b.Property<bool?>("GlasswareIncluded")
                        .HasColumnType("boolean");

                    b.Property<string>("KitchenRequirement")
                        .HasColumnType("text");

                    b.Property<int?>("MaxGuests")
                        .HasColumnType("integer");

                    b.Property<int?>("MinGuests")
                        .HasColumnType("integer");

                    b.Property<string>("OutstationCatering")
                        .HasColumnType("text");

                    b.Property<string>("PricePerHead")
                        .HasColumnType("text");

                    b.Property<string>("ServiceStyle")
                        .HasColumnType("text");

                    b.Property<bool?>("SetupTeardownIncluded")
                        .HasColumnType("boolean");

                    b.Property<bool>("TastingAvailable")
                        .HasColumnType("boolean");

                    b.Property<string>("TastingPolicy")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool?>("WaitstaffIncluded")
                        .HasColumnType("boolean");

                    b.HasKey("ServiceId");

                    b.ToTable("CateringDetails");
                });

            modelBuilder.Entity("Backend.Entities.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CustomerId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("CustomerId");

                    b.HasIndex("UserId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Backend.Entities.DecorationsDetails", b =>
                {
                    b.Property<int>("ServiceId")
                        .HasColumnType("integer");

                    b.Property<string[]>("AvailableSetups")
                        .HasColumnType("text[]");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool?>("CustomMoodboards")
                        .HasColumnType("boolean");

                    b.Property<bool?>("CustomSignageIncluded")
                        .HasColumnType("boolean");

                    b.Property<string>("DesignFeePolicy")
                        .HasColumnType("text");

                    b.Property<string[]>("FloralTypes")
                        .HasColumnType("text[]");

                    b.Property<bool?>("FreeConsultation")
                        .HasColumnType("boolean");

                    b.Property<bool?>("LoungePropsAvailable")
                        .HasColumnType("boolean");

                    b.Property<string>("MinimumBudget")
                        .HasColumnType("text");

                    b.Property<bool>("OutstationDecorAllowed")
                        .HasColumnType("boolean");

                    b.Property<string[]>("PrimaryStyles")
                        .HasColumnType("text[]");

                    b.Property<bool>("ProvidesFlorals")
                        .HasColumnType("boolean");

                    b.Property<bool?>("SameDayTeardownIncluded")
                        .HasColumnType("boolean");

                    b.Property<string>("SetupTimeRequired")
                        .HasColumnType("text");

                    b.Property<string>("TablewareLinens")
                        .HasColumnType("text");

                    b.Property<string>("TravelFeePolicy")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("VenueRestrictions")
                        .HasColumnType("text");

                    b.HasKey("ServiceId");

                    b.ToTable("DecorationsDetails");
                });

            modelBuilder.Entity("Backend.Entities.HotelVenueDetails", b =>
                {
                    b.Property<int>("ServiceId")
                        .HasColumnType("integer");

                    b.Property<string>("AdditionalCharges")
                        .HasColumnType("text");

                    b.Property<string>("BarFacility")
                        .HasColumnType("text");

                    b.Property<bool?>("BasicDecorationIncluded")
                        .HasColumnType("boolean");

                    b.Property<string>("BeverageService")
                        .HasColumnType("text");

                    b.Property<bool?>("BridalSuiteAvailable")
                        .HasColumnType("boolean");

                    b.Property<bool?>("BuffetAvailable")
                        .HasColumnType("boolean");

                    b.Property<bool?>("CakeCuttingAllowed")
                        .HasColumnType("boolean");

                    b.Property<string>("CancellationPolicy")
                        .HasColumnType("text");

                    b.Property<string>("CateringProvidedBy")
                        .HasColumnType("text");

                    b.Property<string>("CeremonyLocation")
                        .HasColumnType("text");

                    b.Property<string>("ComplimentaryBridalSuite")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string[]>("CuisineOptions")
                        .HasColumnType("text[]");

                    b.Property<bool?>("CustomMenuAvailable")
                        .HasColumnType("boolean");

                    b.Property<string>("DecorationPolicy")
                        .HasColumnType("text");

                    b.Property<string>("DepositAmount")
                        .HasColumnType("text");

                    b.Property<bool?>("DepositRequired")
                        .HasColumnType("boolean");

                    b.Property<string>("DjAllowed")
                        .HasColumnType("text");

                    b.Property<string>("ExternalPhotographerAllowed")
                        .HasColumnType("text");

                    b.Property<bool?>("FloralDecorationAvailable")
                        .HasColumnType("boolean");

                    b.Property<bool?>("GuestAccommodationAvailable")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasAccommodation")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasAirConditioning")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasBackupGenerator")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasBeverages")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasCatering")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasCeremony")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasDecoration")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasElevator")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasEntertainment")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasGuestDropOff")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasPhotographyPolicy")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasPolicies")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasVendorLoadingAccess")
                        .HasColumnType("boolean");

                    b.Property<string>("IndoorOutdoor")
                        .HasColumnType("text");

                    b.Property<string>("KitchenFacility")
                        .HasColumnType("text");

                    b.Property<string>("LightingDecoration")
                        .HasColumnType("text");

                    b.Property<string>("LiveBandAllowed")
                        .HasColumnType("text");

                    b.Property<string>("MaxMusicEndTime")
                        .HasColumnType("text");

                    b.Property<string>("MinimumBookingDuration")
                        .HasColumnType("text");

                    b.Property<int?>("MinimumGuestCount")
                        .HasColumnType("integer");

                    b.Property<string>("NumberOfGuestRooms")
                        .HasColumnType("text");

                    b.Property<bool?>("OnSiteAccommodation")
                        .HasColumnType("boolean");

                    b.Property<string>("OutdoorCeremonyCapacity")
                        .HasColumnType("text");

                    b.Property<string>("OutsideBeveragesAllowed")
                        .HasColumnType("text");

                    b.Property<string>("OutsideDecoratorAllowed")
                        .HasColumnType("text");

                    b.Property<string>("OutsideFoodAllowed")
                        .HasColumnType("text");

                    b.Property<string>("OutsideVendorRestrictions")
                        .HasColumnType("text");

                    b.Property<string>("ParkingCapacity")
                        .HasColumnType("text");

                    b.Property<string>("ParkingType")
                        .HasColumnType("text");

                    b.Property<bool?>("PhotographyAllowed")
                        .HasColumnType("boolean");

                    b.Property<string[]>("PhotographyLocations")
                        .HasColumnType("text[]");

                    b.Property<bool?>("PlatedDinnerAvailable")
                        .HasColumnType("boolean");

                    b.Property<string>("PreWeddingShootAllowed")
                        .HasColumnType("text");

                    b.Property<string>("ProjectorScreen")
                        .HasColumnType("text");

                    b.Property<string[]>("RoomTypes")
                        .HasColumnType("text[]");

                    b.Property<bool?>("SeparateCeremonyReceptionSpaces")
                        .HasColumnType("boolean");

                    b.Property<bool?>("StageDecorationAvailable")
                        .HasColumnType("boolean");

                    b.Property<string>("TableDecoration")
                        .HasColumnType("text");

                    b.Property<bool?>("TraditionalMusicAllowed")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ValetParking")
                        .HasColumnType("text");

                    b.Property<string>("VenueSetting")
                        .HasColumnType("text");

                    b.Property<string>("VenueType")
                        .HasColumnType("text");

                    b.Property<string>("WheelchairAccessible")
                        .HasColumnType("text");

                    b.Property<string>("Wifi")
                        .HasColumnType("text");

                    b.HasKey("ServiceId");

                    b.ToTable("HotelVenueDetails");
                });

            modelBuilder.Entity("Backend.Entities.MusicDetails", b =>
                {
                    b.Property<int>("ServiceId")
                        .HasColumnType("integer");

                    b.Property<bool?>("BackupHardwareOnSite")
                        .HasColumnType("boolean");

                    b.Property<bool?>("BreakMusicIncluded")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CustomSongsAllowed")
                        .HasColumnType("text");

                    b.Property<string[]>("Genres")
                        .HasColumnType("text[]");

                    b.Property<string>("LightingRig")
                        .HasColumnType("text");

                    b.Property<string>("LineupSize")
                        .HasColumnType("text");

                    b.Property<bool?>("McServicesIncluded")
                        .HasColumnType("boolean");

                    b.Property<string>("OvertimeRate")
                        .HasColumnType("text");

                    b.Property<string>("PerformanceType")
                        .HasColumnType("text");

                    b.Property<string>("SetDuration")
                        .HasColumnType("text");

                    b.Property<string>("SetupTimeRequired")
                        .HasColumnType("text");

                    b.Property<string>("SoundSystemCapacity")
                        .HasColumnType("text");

                    b.Property<bool>("SoundSystemIncluded")
                        .HasColumnType("boolean");

                    b.Property<bool>("StageLightingIncluded")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("WirelessMics")
                        .HasColumnType("text");

                    b.HasKey("ServiceId");

                    b.ToTable("MusicDetails");
                });

            modelBuilder.Entity("Backend.Entities.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NotificationId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("NotificationId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "IsRead");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Backend.Entities.PhotographyDetails", b =>
                {
                    b.Property<int>("ServiceId")
                        .HasColumnType("integer");

                    b.Property<bool>("AlbumIncluded")
                        .HasColumnType("boolean");

                    b.Property<string>("AlbumPages")
                        .HasColumnType("text");

                    b.Property<string>("AlbumType")
                        .HasColumnType("text");

                    b.Property<bool?>("BackupGear")
                        .HasColumnType("boolean");

                    b.Property<string>("CancellationPolicy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DeliveryTimeframe")
                        .HasColumnType("text");

                    b.Property<string>("DepositAmount")
                        .HasColumnType("text");

                    b.Property<bool>("DepositRequired")
                        .HasColumnType("boolean");

                    b.Property<bool?>("DigitalGalleryIncluded")
                        .HasColumnType("boolean");

                    b.Property<bool?>("DroneAllowed")
                        .HasColumnType("boolean");

                    b.Property<string>("HoursOfCoverage")
                        .HasColumnType("text");

                    b.Property<string[]>("IncludedServices")
                        .HasColumnType("text[]");

                    b.Property<bool?>("OutstationAccommodationRequired")
                        .HasColumnType("boolean");

                    b.Property<string>("PhotographerCount")
                        .HasColumnType("text");

                    b.Property<string>("PhotosDelivered")
                        .HasColumnType("text");

                    b.Property<bool?>("RawFilesIncluded")
                        .HasColumnType("boolean");

                    b.Property<string>("ShootingStyle")
                        .HasColumnType("text");

                    b.Property<string>("TravelOutsideColombo")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string[]>("VideoDeliverables")
                        .HasColumnType("text[]");

                    b.Property<string>("VideoLength")
                        .HasColumnType("text");

                    b.Property<string>("VideographerCount")
                        .HasColumnType("text");

                    b.Property<bool>("VideographyIncluded")
                        .HasColumnType("boolean");

                    b.HasKey("ServiceId");

                    b.ToTable("PhotographyDetails");
                });

            modelBuilder.Entity("Backend.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Backend.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Backend.Entities.Vendor", b =>
                {
                    b.Property<int>("VendorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VendorId"));

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("AltPhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("BusinessHoursJson")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ContactNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CoverImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("OwnerName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("ServiceAreas")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("SocialLinksJson")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Tagline")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("TravelPolicy")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("WebsiteUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("YearsInBusiness")
                        .HasColumnType("integer");

                    b.HasKey("VendorId");

                    b.HasIndex("UserId");

                    b.ToTable("Vendors");
                });

            modelBuilder.Entity("Backend.Entities.VendorDocument", b =>
                {
                    b.Property<int>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DocumentId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DocumentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("VendorId")
                        .HasColumnType("integer");

                    b.HasKey("DocumentId");

                    b.HasIndex("VendorId");

                    b.ToTable("VendorDocuments");
                });

            modelBuilder.Entity("Backend.Entities.VendorGalleryImage", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ImageId"));

                    b.Property<string>("Caption")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("VendorId")
                        .HasColumnType("integer");

                    b.HasKey("ImageId");

                    b.HasIndex("VendorId");

                    b.ToTable("VendorGalleryImages");
                });

            modelBuilder.Entity("Backend.Entities.VendorPerformance", b =>
                {
                    b.Property<int>("PerformanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PerformanceId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CustomerFeedback")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("EventDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("VendorId")
                        .HasColumnType("integer");

                    b.HasKey("PerformanceId");

                    b.HasIndex("VendorId");

                    b.ToTable("VendorPerformances");
                });

            modelBuilder.Entity("Backend.Entities.VendorService", b =>
                {
                    b.Property<int>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ServiceId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("CoverImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsPriceOnRequest")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("Draft");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("VendorId")
                        .HasColumnType("integer");

                    b.HasKey("ServiceId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("VendorId");

                    b.ToTable("VendorServices");
                });

            modelBuilder.Entity("Backend.Entities.VendorServiceImage", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ImageId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsCover")
                        .HasColumnType("boolean");

                    b.Property<int>("ServiceId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("ImageId");

                    b.HasIndex("ServiceId");

                    b.ToTable("VendorServiceImages");
                });

            modelBuilder.Entity("Backend.Entities.VenueSpace", b =>
                {
                    b.Property<int>("VenueSpaceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VenueSpaceId"));

                    b.Property<bool?>("AirConditioned")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("FloatingCapacity")
                        .HasColumnType("integer");

                    b.Property<string>("KeyFeatures")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int?>("SeatedCapacity")
                        .HasColumnType("integer");

                    b.Property<int>("ServiceId")
                        .HasColumnType("integer");

                    b.Property<string>("SpaceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SpaceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("VenueSpaceId");

                    b.HasIndex("ServiceId");

                    b.ToTable("VenueSpaces");
                });

            modelBuilder.Entity("Backend.Entities.Admin", b =>
                {
                    b.HasOne("Backend.Entities.User", "User")
                        .WithOne("Admin")
                        .HasForeignKey("Backend.Entities.Admin", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Entities.CateringDetails", b =>
                {
                    b.HasOne("Backend.Entities.VendorService", "VendorService")
                        .WithOne("CateringDetails")
                        .HasForeignKey("Backend.Entities.CateringDetails", "ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VendorService");
                });

            modelBuilder.Entity("Backend.Entities.Customer", b =>
                {
                    b.HasOne("Backend.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Entities.DecorationsDetails", b =>
                {
                    b.HasOne("Backend.Entities.VendorService", "VendorService")
                        .WithOne("DecorationsDetails")
                        .HasForeignKey("Backend.Entities.DecorationsDetails", "ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VendorService");
                });

            modelBuilder.Entity("Backend.Entities.HotelVenueDetails", b =>
                {
                    b.HasOne("Backend.Entities.VendorService", "VendorService")
                        .WithOne("HotelVenueDetails")
                        .HasForeignKey("Backend.Entities.HotelVenueDetails", "ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VendorService");
                });

            modelBuilder.Entity("Backend.Entities.MusicDetails", b =>
                {
                    b.HasOne("Backend.Entities.VendorService", "VendorService")
                        .WithOne("MusicDetails")
                        .HasForeignKey("Backend.Entities.MusicDetails", "ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VendorService");
                });

            modelBuilder.Entity("Backend.Entities.Notification", b =>
                {
                    b.HasOne("Backend.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Entities.PhotographyDetails", b =>
                {
                    b.HasOne("Backend.Entities.VendorService", "VendorService")
                        .WithOne("PhotographyDetails")
                        .HasForeignKey("Backend.Entities.PhotographyDetails", "ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VendorService");
                });

            modelBuilder.Entity("Backend.Entities.User", b =>
                {
                    b.HasOne("Backend.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Backend.Entities.Vendor", b =>
                {
                    b.HasOne("Backend.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Entities.VendorDocument", b =>
                {
                    b.HasOne("Backend.Entities.Vendor", "Vendor")
                        .WithMany("Documents")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("Backend.Entities.VendorGalleryImage", b =>
                {
                    b.HasOne("Backend.Entities.Vendor", "Vendor")
                        .WithMany("GalleryImages")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("Backend.Entities.VendorPerformance", b =>
                {
                    b.HasOne("Backend.Entities.Vendor", "Vendor")
                        .WithMany()
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("Backend.Entities.VendorService", b =>
                {
                    b.HasOne("Backend.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Entities.Vendor", "Vendor")
                        .WithMany("VendorServices")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("Backend.Entities.VendorServiceImage", b =>
                {
                    b.HasOne("Backend.Entities.VendorService", "Service")
                        .WithMany("Images")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Backend.Entities.VenueSpace", b =>
                {
                    b.HasOne("Backend.Entities.VendorService", "VendorService")
                        .WithMany("VenueSpaces")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VendorService");
                });

            modelBuilder.Entity("Backend.Entities.User", b =>
                {
                    b.Navigation("Admin");
                });

            modelBuilder.Entity("Backend.Entities.Vendor", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("GalleryImages");

                    b.Navigation("VendorServices");
                });

            modelBuilder.Entity("Backend.Entities.VendorService", b =>
                {
                    b.Navigation("CateringDetails");

                    b.Navigation("DecorationsDetails");

                    b.Navigation("HotelVenueDetails");

                    b.Navigation("Images");

                    b.Navigation("MusicDetails");

                    b.Navigation("PhotographyDetails");

                    b.Navigation("VenueSpaces");
                });
#pragma warning restore 612, 618
        }
    }
}
