using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Backend.Migrations
{
    /// <inheritdoc />
    public partial class AddCustomerProfilePhotoAndNotificationPreferences : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                ALTER TABLE ""Customers"" 
                ADD COLUMN IF NOT EXISTS ""ProfilePhotoUrl"" character varying(500);
            ");

            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""CustomerNotificationPreferences"" (
                    ""PreferenceId"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""CustomerId"" integer NOT NULL,
                    ""InquiryUpdates"" boolean NOT NULL DEFAULT TRUE,
                    ""PriceChanges"" boolean NOT NULL DEFAULT TRUE,
                    ""CreatedAt"" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    ""UpdatedAt"" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    CONSTRAINT ""PK_CustomerNotificationPreferences"" PRIMARY KEY (""PreferenceId""),
                    CONSTRAINT ""FK_CustomerNotificationPreferences_Customers_CustomerId"" FOREIGN KEY (""CustomerId"") REFERENCES ""Customers"" (""CustomerId"") ON DELETE CASCADE
                );
            ");

            migrationBuilder.Sql(@"
                CREATE UNIQUE INDEX IF NOT EXISTS ""IX_CustomerNotificationPreferences_CustomerId"" 
                ON ""CustomerNotificationPreferences"" (""CustomerId"");
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                DROP TABLE IF EXISTS ""CustomerNotificationPreferences"";
            ");

            migrationBuilder.Sql(@"
                ALTER TABLE ""Customers"" 
                DROP COLUMN IF EXISTS ""ProfilePhotoUrl"";
            ");
        }
    }
}
